export enum EntityStatus {
    NEW = 'NEW',
    VALIDATED = 'VALIDATED',
    INVALIDATED = 'INVALIDATED',
    UNAVAILABLE = 'UNAVAILABLE',
    AVAILABLE = 'AVAILABLE',
    BLOCKED = 'BLOCKED',
    DELETED = 'DELETED'
}