export enum EmailType {
    // Commandes
    ORDER_CREATED_CUSTOMER = 'ORDER_CREATED_CUSTOMER',
    ORDER_CREATED_RESTAURANT = 'ORDER_CREATED_RESTAURANT',
    ORDER_STATUS_UPDATED_CUSTOMER = 'ORDER_STATUS_UPDATED_CUSTOMER',
    ORDER_STATUS_UPDATED_RESTAURANT = 'ORDER_STATUS_UPDATED_RESTAURANT',
    ORDER_CANCELLED_BY_RESTAURANT = 'ORDER_CANCELLED_BY_RESTAURANT',

    // Paiements
    PAYMENT_SUCCESS_CUSTOMER = 'PAYMENT_SUCCESS_CUSTOMER',
    PAYMENT_SUCCESS_RESTAURANT = 'PAYMENT_SUCCESS_RESTAURANT',

    // Fidélité
    LOYALTY_POINTS_EARNED = 'LOYALTY_POINTS_EARNED',
    LOYALTY_POINTS_REDEEMED = 'LOYALTY_POINTS_REDEEMED',
    LOYALTY_LEVEL_UP = 'LOYALTY_LEVEL_UP',
    POINTS_EXPIRING_SOON = 'POINTS_EXPIRING_SOON',

    // Promotions
    PROMOTION_USED = 'PROMOTION_USED',
    PROMOTION_AVAILABLE = 'PROMOTION_AVAILABLE',

    // Utilisateurs
    WELCOME_NEW_CUSTOMER = 'WELCOME_NEW_CUSTOMER',
    NEW_USER_RESTAURANT = 'NEW_USER_RESTAURANT',

    // Catalogue
    DISH_CREATED = 'DISH_CREATED',
    CATEGORY_CREATED = 'CATEGORY_CREATED'
}