export enum Modules {
  DASHBOARD = 'dashboard',
  COMMANDES = 'orders',
  MENUS = 'menus',
  MARKETING = 'marketing',
  CLIENTS = 'clients',
  INVENTAIRE = 'inventory',
  RESTAURANTS = 'restaurants',
  PERSONNELS = 'personnel',
  PROMOTIONS = 'promos',
  FIDELITE = 'loyalty',
  MESSAGES = 'inbox',
  CARD_NATION = 'card_nation',
  COMMENTAIRES = 'reviews',
  ALL = 'all',
}