export enum Modules {
  DASHBOARD = 'dashboard',
  COMMANDES = 'orders',
  MENUS = 'menus',
  MARKETING = 'marketing',
  CLIENTS = 'clients',
  INVENTAIRE = 'inventory',
  RESTAURANTS = 'restaurants',
  PERSONNELS = 'personnel',
  LIVREURS = 'livreurs',
  PROMOTIONS = 'promos',
  FIDELITE = 'loyalty',
  MESSAGES = 'inbox',
  CARD_NATION = 'card_nation',
  COMMENTAIRES = 'reviews',
  SETTINGS = 'settings',
  BASE_DONNEES = 'base_donnees',
  /** Conversion des inscrits qui n'ont jamais commandé (module Prospects). */
  PROSPECTS = 'prospects',
  CALLS = 'calls',
  AUDIT = 'audit',
  ALL = 'all',
}